TRANSLATION_DICT={
        'IN':"INTERJEIÇÃO",
        'PREP':"PREPOSIÇÃO",
        'PREP+ART':"PREPOSIÇÃO#ARTIGO",
        'PREP+PRO':"PREPOSIÇÃO#PRONOME",
        'V':"VERBO",
        'VAUX':"VERBO#AUXILIAR",
        'PCP':"PARTICÍPIO",
        'PDEN':"PALAVRA#DENOTATIVA",
        'CUR':"MOEDA",
        'NPROP':"NOME#PRÓPRIO",
        'NUM':"NUMERAL",
        'PROADJ':"PRONOME#ADJETIVO",
        'PROADJETIVO':"PRONOME#ADJETIVO",
        'PROSUB':"PRONOME#SUBSTANTIVO",
        'PROPESS':"PRONOME#PESSOAL",
        'PRO-KS':"PRONOME#CONECTIVO#SUBORDINATIVO",
        'PRO-KS-REL':"PRONOME#CONECTIVO#SUBORDINATIVO#RELATIVO",
        'ADV-KS':"ADVÉRBIO#CONECTIVO#SUBORDINATIVO",
        'ADV-KS-REL':"ADVÉRBIO#RELATIVO#SUBORDINATIVO",
        'ADVÉRBIOETIVO':"ADJETIVO",
        'KC':"CONJUNÇÃO#COORDENATIVA",
        'KS':"CONJUNÇÃO#SUBORDINATIVA",
        'v-fin':"VERBO#FINITO",
        'v-inf':"VERBO#INFINITO",
        'v-pcp':"VERBO#PARTICÍPIO",
        'v-ger':"VERBO#GERÚNDIO",
        'pron-pers':"PRONOME#PESSOAL",
        'pron-det':"PRONOME#DETERMINATIVO",
        'pron-indp':"PRONOME#INDEPENDENTE",
        'adv':"ADVÉRBIO",
        'art':"ARTIGO",
        'n':"SUBSTANTIVO",
        'N':"SUBSTANTIVO",
        'prop':"NOME#PRÓPRIO",
        'adj':"ADJETIVO",
        'num':"NUMERAL",
        'prp':"PREPOSIÇÃO",
        'intj':"INTERJEIÇÃO",
        'kc':"NOME#PRÓPRIO",
        'conj-c':"CONJUNÇÃO#COORDENATIVA",
        'conj-s':"CONJUNÇÃO#SUBORDINATIVA",
        }

BK_COLOR_DICT = {
    "SUBSTANTIVO": "#fd2c2c",
    "AUXILIAR": "#6aa84f",
    "NOME#PRÓPRIO": "#fd2c2c",
    "VERBO": "#6aa84f",
    "VERBO#AUXILIAR": "#6aa84f",
    "VERBO#LIGAÇÃO": "#6aa84f",
    "VERBO#PRONOME": "#6aa84f",
    "VERBO#PRONOME#DESINENCIA": "#6aa84f",
    "VERBO#FINITO": "#6aa84f",
    "VERBO#INFINITIVO": "#6aa84f",
    "VERBO#PARTICÍPIO": "#6aa84f",
    "VERBO#GERÚNDIO": "#6aa84f",
    "ADJETIVO": "#0000ff",
    "ARTIGO": "#5B850C",
    "PRONOME": "#b77a7a",
    "PRONOME#ADJETIVO": "#b77a7a",
    "PRONOME#SUBSTANTIVO": "#b77a7a",
    "PRONOME#PESSOAL": "#b77a7a",
    "PRONOME#CONECTIVO#SUBORDINATIVO": "#b77a7a",
    "PRONOME#CONECTIVO#SUBORDINATIVO#RELATIVO": "#b77a7a",
    "PRONOME#DETERMINATIVO": "#b77a7a",
    "PRONOME#INDEPENDENTE": "#b77a7a",
    "NUMERAL": "#ef8ccd",
    "ADVÉRBIO": "#9900ff",
    "ADVÉRBIO#CONECTIVO#SUBORDINATIVO": "#9900ff",
    "ADVÉRBIO#RELATIVO#SUBORDINATIVO": "#9900ff",
    "PREPOSIÇÃO": "#999999",
    "PREPOSIÇÃO#PRONOME": "#999999",
    "PREPOSIÇÃO#ARTIGO": "#999999",
    "PREPOSIÇÃO#ADVÉRBIO": "#999999",
    "CONJUNÇÃO": "#c9c9c9",
    "CONJUNÇÃO#COORDENATIVA": "#c9c9c9",
    "CONJUNÇÃO#SUBORDINATIVA": "#c9c9c9",
    "OUTROS": "#000000",
    "SIMB": "black",
    "INTERJEIÇÃO": "#000000",
    "PONTUAÇÃO": "black",
    "PARTICÍPIO": "black",
    "PALAVRA#DENOTATIVA": "black",
    "MOEDA": "black",
}
tag_redirect = {
    "VERBO:relcl":"VERBO",
}


COLOR_DICT = {key: "white" for key in BK_COLOR_DICT}
