BK_COLOR_DICT = {
    "SUBSTANTIVO": "#fd2c2c",
    "AUXILIAR": "#6aa84f",
    "NOME#PRÓPRIO": "#fd2c2c",
    "VERBO": "#6aa84f",
    "VERBO#AUXILIAR": "#6aa84f",
    "VERBO#LIGAÇÃO": "#6aa84f",
    "VERBO#PRONOME": "#6aa84f",
    "VERBO#PRONOME#DESINENCIA": "#6aa84f",
    "VERBO#FINITO": "#6aa84f",
    "VERBO#INFINITIVO": "#6aa84f",
    "VERBO#PARTICÍPIO": "#6aa84f",
    "VERBO#GERÚNDIO": "#6aa84f",
    "ADJETIVO": "#0000ff",
    "ARTIGO": "#afa",
    "PRONOME": "#b77a7a",
    "PRONOME#ADJETIVO": "#b77a7a",
    "PRONOME#SUBSTANTIVO": "#b77a7a",
    "PRONOME#PESSOAL": "#b77a7a",
    "PRONOME#CONECTIVO#SUBORDINATIVO": "#b77a7a",
    "PRONOME#CONECTIVO#SUBORDINATIVO#RELATIVO": "#b77a7a",
    "PRONOME#DETERMINATIVO": "#b77a7a",
    "PRONOME#INDEPENDENTE": "#b77a7a",
    "NUMERAL": "#ef8ccd",
    "ADVÉRBIO": "#9900ff",
    "ADVÉRBIO#CONECTIVO#SUBORDINATIVO": "#9900ff",
    "ADVÉRBIO#RELATIVO#SUBORDINATIVO": "#9900ff",
    "PREPOSIÇÃO": "#999999",
    "PREPOSIÇÃO#PRONOME": "#999999",
    "PREPOSIÇÃO#ARTIGO": "#999999",
    "PREPOSIÇÃO#ADVÉRBIO": "#999999",
    "CONJUNÇÃO": "#c9c9c9",
    "CONJUNÇÃO#COORDENATIVA": "#c9c9c9",
    "CONJUNÇÃO#SUBORDINATIVA": "#c9c9c9",
    "OUTROS": "#000000",
    "SIMB": "white",
    "INTERJEIÇÃO": "#000000",
    "PONTUAÇÃO": "white",
    "PARTICÍPIO": "white",
    "PALAVRA#DENOTATIVA": "white",
    "MOEDA": "white",
}
tag_redirect = {
    "VERBO:relcl":"VERBO",
}


COLOR_DICT = {key: "white" for key in BK_COLOR_DICT}